import {
  EvidenceDepth,
  SignalCategory,
  SignalKey,
  SignalSource,
} from "./signalTypes";

export interface SignalDefinition {
  key: SignalKey;
  label: string;
  category: SignalCategory;
  defaultSource: SignalSource;
  defaultDepth: EvidenceDepth;
  description: string;
}

export const SIGNAL_REGISTRY: Record<SignalKey, SignalDefinition> = {
  rating: {
    key: "rating",
    label: "Rating",
    category: "reputation",
    defaultSource: "google_places",
    defaultDepth: "base",
    description: "Average public rating from provider data.",
  },
  review_count: {
    key: "review_count",
    label: "Review Count",
    category: "reputation",
    defaultSource: "google_places",
    defaultDepth: "base",
    description: "Total review volume from provider data.",
  },
  website_exists: {
    key: "website_exists",
    label: "Website Exists",
    category: "digitalPresence",
    defaultSource: "provider",
    defaultDepth: "base",
    description: "Whether the business has a website URL.",
  },
  social_presence: {
    key: "social_presence",
    label: "Social Presence",
    category: "digitalPresence",
    defaultSource: "provider",
    defaultDepth: "base",
    description: "Whether the business appears to have social presence.",
  },
  classification_confidence: {
    key: "classification_confidence",
    label: "Classification Confidence",
    category: "evidenceConfidence",
    defaultSource: "classification",
    defaultDepth: "base",
    description: "Confidence of deterministic business classification.",
  },
  is_good_fit: {
    key: "is_good_fit",
    label: "Good Fit",
    category: "businessStrength",
    defaultSource: "classification",
    defaultDepth: "base",
    description: "Whether the lead matches the intended target fit.",
  },
  website_has_contact_page: {
    key: "website_has_contact_page",
    label: "Website Has Contact Page",
    category: "digitalPresence",
    defaultSource: "website_scan",
    defaultDepth: "light",
    description: "Whether the website includes a contact page.",
  },
  website_has_booking_cta: {
    key: "website_has_booking_cta",
    label: "Website Has Booking CTA",
    category: "opportunityGap",
    defaultSource: "website_scan",
    defaultDepth: "light",
    description: "Whether the website has a clear booking or inquiry CTA.",
  },
  website_has_clear_offer: {
    key: "website_has_clear_offer",
    label: "Website Has Clear Offer",
    category: "opportunityGap",
    defaultSource: "website_scan",
    defaultDepth: "light",
    description: "Whether the service offering is clearly explained.",
  },
  website_mobile_friendly: {
    key: "website_mobile_friendly",
    label: "Website Mobile Friendly",
    category: "digitalPresence",
    defaultSource: "website_scan",
    defaultDepth: "light",
    description: "Whether the website appears mobile-friendly.",
  },
  social_platform_count: {
    key: "social_platform_count",
    label: "Social Platform Count",
    category: "digitalPresence",
    defaultSource: "social_scan",
    defaultDepth: "light",
    description: "Number of detected social platforms.",
  },
  social_last_post_days: {
    key: "social_last_post_days",
    label: "Social Last Post Days",
    category: "digitalPresence",
    defaultSource: "social_scan",
    defaultDepth: "light",
    description: "Days since most recent visible social post.",
  },
  owner_response_presence: {
    key: "owner_response_presence",
    label: "Owner Response Presence",
    category: "reputation",
    defaultSource: "google_places",
    defaultDepth: "light",
    description: "Whether the owner appears to respond to reviews.",
  },
  review_velocity_estimate: {
    key: "review_velocity_estimate",
    label: "Review Velocity Estimate",
    category: "reputation",
    defaultSource: "google_places",
    defaultDepth: "light",
    description: "Estimated speed of review accumulation.",
  },
  website_page_speed_score: {
    key: "website_page_speed_score",
    label: "Website Page Speed Score",
    category: "digitalPresence",
    defaultSource: "website_scan",
    defaultDepth: "deep",
    description: "Measured performance score for website speed.",
  },
  website_seo_structure_score: {
    key: "website_seo_structure_score",
    label: "Website SEO Structure Score",
    category: "digitalPresence",
    defaultSource: "website_scan",
    defaultDepth: "deep",
    description: "Measured structural SEO quality of the website.",
  },
  website_cta_strength: {
    key: "website_cta_strength",
    label: "Website CTA Strength",
    category: "opportunityGap",
    defaultSource: "website_scan",
    defaultDepth: "deep",
    description: "How strong and actionable the website CTA system is.",
  },
  booking_flow_quality: {
    key: "booking_flow_quality",
    label: "Booking Flow Quality",
    category: "opportunityGap",
    defaultSource: "website_scan",
    defaultDepth: "deep",
    description: "Quality and friction level of booking or inquiry flow.",
  },
  competitor_density: {
    key: "competitor_density",
    label: "Competitor Density",
    category: "stabilityRisk",
    defaultSource: "market_scan",
    defaultDepth: "deep",
    description: "Density of relevant competitors in the local market.",
  },
  local_market_saturation: {
    key: "local_market_saturation",
    label: "Local Market Saturation",
    category: "stabilityRisk",
    defaultSource: "market_scan",
    defaultDepth: "deep",
    description: "Estimated saturation of the local service market.",
  },
  brand_content_quality: {
    key: "brand_content_quality",
    label: "Brand Content Quality",
    category: "businessStrength",
    defaultSource: "social_scan",
    defaultDepth: "deep",
    description: "Evaluated quality of the business brand/content presence.",
  },
  posting_frequency_score: {
    key: "posting_frequency_score",
    label: "Posting Frequency Score",
    category: "digitalPresence",
    defaultSource: "social_scan",
    defaultDepth: "deep",
    description: "Evaluated consistency of social posting activity.",
  },
};
