-- 0007_remove_user_profiles_allow_all.sql
--
-- CRITICAL SECURITY FIX. Found via a deeper audit of actual RLS policy
-- content (not just which tables have RLS enabled). user_profiles had a
-- policy named "allow_all" (ALL commands, qual=true, with_check=true)
-- sitting ALONGSIDE otherwise correctly-scoped policies
-- (auth.uid() = id for select/update/insert, delete blocked entirely).
--
-- In Postgres RLS, multiple permissive policies for the same command
-- combine with OR — so this one open policy overrode every carefully
-- scoped policy on the same table, making every user's business profile
-- (name, target geography, offer description, capabilities) readable AND
-- writable by anyone, regardless of the other policies' intent.
--
-- This was NOT just theoretical risk: it was also functionally load-
-- bearing, because app/api/profile/route.ts's GET handler was using the
-- anon-key singleton client (no forwarded session) rather than a
-- session-aware server client, meaning auth.uid() always evaluated to
-- NULL there — the scoped policies could never have matched on their own.
-- That client bug is fixed in the same commit as this migration
-- (app/api/profile/route.ts now uses createSupabaseServer()). Do not
-- apply this migration without that code change already deployed, or
-- profile reads will silently return nothing for every user.

drop policy if exists "allow_all" on user_profiles;