-- Baseline schema snapshot for Vantio Revenue (project brkkhszaojfgdvqxtkta)
-- Generated as a disaster-recovery baseline: no migration history existed prior to this.
-- Idempotent: uses IF NOT EXISTS / guarded DO blocks so it is safe to run against the live DB
-- (which already has these objects) purely to register a tracked baseline in migration history,
-- and to have the schema captured in git (leadgen-os repo) independent of the Supabase project.
-- NOTE: this captures STRUCTURE only (tables, columns, PKs, FKs, RLS enable flags), not data,
-- and does not reproduce RLS POLICY definitions, indexes beyond PKs, sequences/defaults beyond
-- what list_tables exposes, functions, or triggers. It is not a substitute for Supabase's own
-- Point-in-Time-Recovery / project backups, which should still be enabled for real data protection.

-- Sequences referenced by nextval() defaults below
CREATE SEQUENCE IF NOT EXISTS public.company_classifications_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.lead_outcomes_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.lead_sequences_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.provider_runs_id_seq;

-- Table: public.searches (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.searches (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "niche" text,
  "location" text,
  "company_size" text,
  "social_presence" text,
  "created_at" timestamp DEFAULT now(),
  "user_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.searches ENABLE ROW LEVEL SECURITY;

-- Table: public.companies_raw (1078 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.companies_raw (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "source" text DEFAULT ''::text,
  "source_id" text DEFAULT ''::text,
  "payload" jsonb,
  "created_at" timestamp DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.companies_raw ENABLE ROW LEVEL SECURITY;

-- Table: public.companies_normalized (1078 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.companies_normalized (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "raw_id" bigint,
  "name" text DEFAULT ''::text,
  "address" text,
  "city" text,
  "country" text,
  "website" text,
  "categories" text[],
  "rating" numeric,
  "review_count" integer,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "opportunity_signals" jsonb,
  "primary_insight" jsonb,
  "cached_score" jsonb,
  "signal_hash" text,
  "duplicate_of_raw_id" bigint,
  "normalized_domain" text,
  PRIMARY KEY ("id")
);
ALTER TABLE public.companies_normalized ENABLE ROW LEVEL SECURITY;

-- Table: public.company_classifications (1078 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.company_classifications (
  "id" bigint DEFAULT nextval('company_classifications_id_seq'::regclass) NOT NULL,
  "raw_id" bigint NOT NULL,
  "primary_industry" text NOT NULL,
  "sub_niche" text NOT NULL,
  "service_type" text NOT NULL,
  "b2b_b2c" text NOT NULL,
  "is_good_fit" boolean NOT NULL,
  "fit_reason" text NOT NULL,
  "confidence" integer NOT NULL,
  "source" text NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.company_classifications ENABLE ROW LEVEL SECURITY;

-- Table: public.provider_runs (180 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.provider_runs (
  "id" bigint DEFAULT nextval('provider_runs_id_seq'::regclass) NOT NULL,
  "provider" text NOT NULL,
  "intent_hash" text NOT NULL,
  "request_id" text,
  "intent" jsonb NOT NULL,
  "status" text DEFAULT 'queued'::text NOT NULL,
  "fetched_count" integer DEFAULT 0 NOT NULL,
  "returned_count" integer DEFAULT 0 NOT NULL,
  "inserted_raw" integer DEFAULT 0 NOT NULL,
  "skipped_duplicates" integer DEFAULT 0 NOT NULL,
  "next_cursor" text,
  "exhausted" boolean DEFAULT false NOT NULL,
  "error_code" text,
  "error_message" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "provider_cursor" text,
  "provider_exhausted" boolean DEFAULT false,
  PRIMARY KEY ("id")
);
ALTER TABLE public.provider_runs ENABLE ROW LEVEL SECURITY;

-- Table: public.rate_limits (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.rate_limits (
  "key" text NOT NULL,
  "window_start_ms" bigint NOT NULL,
  "count" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("key", "window_start_ms")
);
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

-- Table: public.provider_run_raws (3625 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.provider_run_raws (
  "run_id" bigint NOT NULL,
  "raw_id" bigint NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("run_id", "raw_id")
);
ALTER TABLE public.provider_run_raws ENABLE ROW LEVEL SECURITY;

-- Table: public.user_profiles (2 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.user_profiles (
  "id" uuid NOT NULL,
  "line_of_business" text,
  "capabilities" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "capabilities_data" jsonb,
  "profile_data" jsonb,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Table: public.lead_outcomes (1 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.lead_outcomes (
  "id" bigint DEFAULT nextval('lead_outcomes_id_seq'::regclass) NOT NULL,
  "run_id" bigint NOT NULL,
  "lead_id" text NOT NULL,
  "user_id" uuid,
  "contacted" boolean DEFAULT false NOT NULL,
  "replied" boolean DEFAULT false NOT NULL,
  "booked_call" boolean DEFAULT false NOT NULL,
  "closed" boolean DEFAULT false NOT NULL,
  "revenue" numeric,
  "notes" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "tonality" text,
  "angle_type" text,
  "followup_date" date,
  "lost_reason" text,
  "score_at_outreach" integer,
  "company_name" text,
  "contacted_at" timestamptz,
  "replied_at" timestamptz,
  "booked_call_at" timestamptz,
  "closed_at" timestamptz,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.lead_outcomes ENABLE ROW LEVEL SECURITY;

-- Table: public.waitlist (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.waitlist (
  "email" text NOT NULL,
  "plan" text,
  "created_at" timestamptz DEFAULT now(),
  "beta_user" boolean DEFAULT false,
  "beta_plan" text,
  "beta_join_date" timestamptz,
  "beta_source" text,
  PRIMARY KEY ("email")
);
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Table: public.contact_submissions (2 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.contact_submissions (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "subject" text,
  "message" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

-- Table: public.deep_scan_usage (1 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.deep_scan_usage (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.deep_scan_usage ENABLE ROW LEVEL SECURITY;

-- Table: public.lead_deep_scans (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.lead_deep_scans (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "source_id" text NOT NULL,
  "lead_id" text NOT NULL,
  "user_id" text NOT NULL,
  "scan_result" jsonb NOT NULL,
  "derived_signals" jsonb NOT NULL,
  "scanned_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.lead_deep_scans ENABLE ROW LEVEL SECURITY;

-- Table: public.support_tickets (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.support_tickets (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid,
  "user_email" text,
  "user_plan" text,
  "business_name" text,
  "summary" text,
  "transcript" text NOT NULL,
  "status" text DEFAULT 'needs_human'::text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- Table: public.outreach_emails (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.outreach_emails (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "lead_id" text,
  "run_id" integer,
  "company_name" text,
  "recipient_email" text NOT NULL,
  "subject" text NOT NULL,
  "body" text NOT NULL,
  "sender_name" text,
  "sent_at" timestamptz DEFAULT now() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.outreach_emails ENABLE ROW LEVEL SECURITY;

-- Table: public.outreach_templates (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.outreach_templates (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "channel" text DEFAULT 'email'::text NOT NULL,
  "subject" text,
  "body" text NOT NULL,
  "tone" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.outreach_templates ENABLE ROW LEVEL SECURITY;

-- Table: public.lead_collections (3 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.lead_collections (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "color" text DEFAULT '#c9a84c'::text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.lead_collections ENABLE ROW LEVEL SECURITY;

-- Table: public.lead_collection_items (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.lead_collection_items (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "collection_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "lead_id" text NOT NULL,
  "run_id" integer,
  "company_name" text,
  "notes" text,
  "added_at" timestamptz DEFAULT now() NOT NULL,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.lead_collection_items ENABLE ROW LEVEL SECURITY;

-- Table: public.lead_sequences (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.lead_sequences (
  "id" bigint DEFAULT nextval('lead_sequences_id_seq'::regclass) NOT NULL,
  "lead_id" text NOT NULL,
  "run_id" integer NOT NULL,
  "user_id" uuid,
  "company_name" text,
  "step" integer NOT NULL,
  "day_offset" integer NOT NULL,
  "scheduled_date" date NOT NULL,
  "channel" text NOT NULL,
  "subject" text,
  "message" text NOT NULL,
  "objective" text NOT NULL,
  "cta" text NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "cadence_type" text DEFAULT 'standard'::text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.lead_sequences ENABLE ROW LEVEL SECURITY;

-- Table: public.outreach_usage (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.outreach_usage (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id" uuid,
  "type" text DEFAULT 'message'::text,
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.outreach_usage ENABLE ROW LEVEL SECURITY;

-- Table: public.deep_search_usage (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.deep_search_usage (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id" uuid,
  "created_at" timestamptz DEFAULT now(),
  PRIMARY KEY ("id")
);
ALTER TABLE public.deep_search_usage ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_invitations (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_invitations (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "email" text NOT NULL,
  "token_hash" text NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "accepted_at" timestamptz,
  "accepted_user_id" uuid,
  "created_by" text,
  "notes" text,
  "company_name" text,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_invitations ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_memberships (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_memberships (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "invitation_id" uuid,
  "status" text DEFAULT 'active'::text NOT NULL,
  "timezone" text DEFAULT 'Europe/Stockholm'::text NOT NULL,
  "activated_at" timestamptz DEFAULT now() NOT NULL,
  "hard_end_at" timestamptz NOT NULL,
  "active_days_used" integer DEFAULT 0 NOT NULL,
  "last_active_date" date,
  "extended_days" integer DEFAULT 0 NOT NULL,
  "extension_granted_by" text,
  "extension_granted_at" timestamptz,
  "expired_at" timestamptz,
  "revoked_at" timestamptz,
  "final_interview_completed" boolean DEFAULT false NOT NULL,
  "final_interview_completed_at" timestamptz,
  "required_feedback_completed" boolean DEFAULT false NOT NULL,
  "required_feedback_completed_at" timestamptz,
  "internal_notes" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "converted_at" timestamptz,
  "monetary_ceiling_micro_usd" bigint,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_memberships ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_usage (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_usage (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "feature" text NOT NULL,
  "idempotency_key" text,
  "status" text DEFAULT 'reserved'::text NOT NULL,
  "cost_micro_usd" bigint DEFAULT 0 NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "committed_at" timestamptz,
  "released_at" timestamptz,
  "provider" text,
  "model" text,
  "request_id" text,
  "related_lead_id" text,
  "related_run_id" bigint,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_usage ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_feature_feedback (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_feature_feedback (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "feature_key" text NOT NULL,
  "feature_version" text DEFAULT 'v1'::text NOT NULL,
  "rating" integer,
  "not_used_enough" boolean DEFAULT false NOT NULL,
  "reason_key" text,
  "free_text" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_feature_feedback ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_lead_feedback (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_lead_feedback (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "lead_id" text NOT NULL,
  "run_id" bigint,
  "accurate" boolean,
  "comment" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_lead_feedback ENABLE ROW LEVEL SECURITY;

-- Table: public.analytics_events (10 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.analytics_events (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id" uuid,
  "event_name" text NOT NULL,
  "properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_tutorial_progress (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_tutorial_progress (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "tutorial_key" text NOT NULL,
  "tutorial_version" text DEFAULT 'v1'::text NOT NULL,
  "current_step" integer DEFAULT 0 NOT NULL,
  "started_at" timestamptz DEFAULT now() NOT NULL,
  "completed_at" timestamptz,
  "skipped_at" timestamptz,
  "replay_count" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_tutorial_progress ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_discount_grants (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_discount_grants (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "source" text DEFAULT 'private_beta'::text NOT NULL,
  "percent" integer DEFAULT 30 NOT NULL,
  "duration_months" integer DEFAULT 12 NOT NULL,
  "eligible_at" timestamptz DEFAULT now() NOT NULL,
  "redemption_deadline" timestamptz,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "redeemed_at" timestamptz,
  "subscription_reference" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_discount_grants ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_testimonials (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_testimonials (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "membership_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "approved_quote" text,
  "approved_name" text,
  "approved_role" text,
  "approved_company" text,
  "logo_permission" boolean DEFAULT false NOT NULL,
  "photo_permission" boolean DEFAULT false NOT NULL,
  "permitted_channels" text[] DEFAULT '{}'::text[] NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "approved_at" timestamptz,
  "revoked_at" timestamptz,
  "internal_notes" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_testimonials ENABLE ROW LEVEL SECURITY;

-- Table: public.beta_feature_allowances (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.beta_feature_allowances (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "membership_id" uuid NOT NULL,
  "feature" text NOT NULL,
  "daily_limit" integer,
  "total_limit" integer,
  "updated_by" text NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.beta_feature_allowances ENABLE ROW LEVEL SECURITY;

-- Table: public.user_search_runs (16 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.user_search_runs (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id" uuid NOT NULL,
  "run_id" bigint NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "market_id" uuid,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.user_search_runs ENABLE ROW LEVEL SECURITY;

-- Table: public.platform_settings (1 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.platform_settings (
  "key" text NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL,
  "updated_by" text,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("key")
);
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

-- Table: public.user_subscriptions (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  "user_id" uuid NOT NULL,
  "plan" text NOT NULL,
  "period" text NOT NULL,
  "currency" text NOT NULL,
  "status" text NOT NULL,
  "stripe_customer_id" text NOT NULL,
  "stripe_subscription_id" text NOT NULL,
  "current_period_end" timestamptz,
  "cancel_at_period_end" boolean DEFAULT false NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("user_id")
);
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;

-- Table: public.company_intelligence (75 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.company_intelligence (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id" uuid NOT NULL,
  "raw_id" bigint NOT NULL,
  "signal_hash" text NOT NULL,
  "score" jsonb NOT NULL,
  "scoring_model_version" text DEFAULT 'v1'::text NOT NULL,
  "scored_at" timestamptz DEFAULT now() NOT NULL,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.company_intelligence ENABLE ROW LEVEL SECURITY;

-- Table: public.markets (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.markets (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "niche" text NOT NULL,
  "location" text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "last_refreshed_at" timestamptz,
  "workspace_id" uuid,
  PRIMARY KEY ("id")
);
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;

-- Table: public.workspaces (4 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.workspaces (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "owner_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;

-- Table: public.workspace_members (4 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.workspace_members (
  "workspace_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" text DEFAULT 'member'::text NOT NULL,
  "joined_at" timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY ("workspace_id", "user_id")
);
ALTER TABLE public.workspace_members ENABLE ROW LEVEL SECURITY;

-- Table: public.workspace_invitations (0 rows at time of capture)
CREATE TABLE IF NOT EXISTS public.workspace_invitations (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "workspace_id" uuid NOT NULL,
  "invited_email" text NOT NULL,
  "invited_by" uuid NOT NULL,
  "token" uuid DEFAULT gen_random_uuid() NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "accepted_at" timestamptz,
  PRIMARY KEY ("id")
);
ALTER TABLE public.workspace_invitations ENABLE ROW LEVEL SECURITY;

-- Foreign key constraints (added after all tables exist, guarded against duplicates)
DO $$ BEGIN
  ALTER TABLE public.provider_run_raws ADD CONSTRAINT "provider_run_raws_raw_id_fkey" FOREIGN KEY ("raw_id") REFERENCES public.companies_raw ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.company_classifications ADD CONSTRAINT "company_classifications_raw_id_fkey" FOREIGN KEY ("raw_id") REFERENCES public.companies_raw ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.provider_run_raws ADD CONSTRAINT "provider_run_raws_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES public.provider_runs ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.user_search_runs ADD CONSTRAINT "user_search_runs_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES public.provider_runs ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_outcomes ADD CONSTRAINT "lead_outcomes_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES public.provider_runs ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.user_profiles ADD CONSTRAINT "user_profiles_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.user_profiles ADD CONSTRAINT "user_profiles_id_fkey" FOREIGN KEY ("id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_outcomes ADD CONSTRAINT "lead_outcomes_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.outreach_emails ADD CONSTRAINT "outreach_emails_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.outreach_emails ADD CONSTRAINT "outreach_emails_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.outreach_templates ADD CONSTRAINT "outreach_templates_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.outreach_templates ADD CONSTRAINT "outreach_templates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_collections ADD CONSTRAINT "lead_collections_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_collection_items ADD CONSTRAINT "lead_collection_items_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES public.lead_collections ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_collections ADD CONSTRAINT "lead_collections_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_collection_items ADD CONSTRAINT "lead_collection_items_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_collection_items ADD CONSTRAINT "lead_collection_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_sequences ADD CONSTRAINT "lead_sequences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.lead_sequences ADD CONSTRAINT "lead_sequences_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.outreach_usage ADD CONSTRAINT "outreach_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.deep_search_usage ADD CONSTRAINT "deep_search_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_invitations ADD CONSTRAINT "beta_invitations_accepted_user_id_fkey" FOREIGN KEY ("accepted_user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_memberships ADD CONSTRAINT "beta_memberships_invitation_id_fkey" FOREIGN KEY ("invitation_id") REFERENCES public.beta_invitations ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_memberships ADD CONSTRAINT "beta_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_usage ADD CONSTRAINT "beta_usage_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_feature_feedback ADD CONSTRAINT "beta_feature_feedback_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_lead_feedback ADD CONSTRAINT "beta_lead_feedback_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_tutorial_progress ADD CONSTRAINT "beta_tutorial_progress_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_discount_grants ADD CONSTRAINT "beta_discount_grants_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_testimonials ADD CONSTRAINT "beta_testimonials_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_feature_allowances ADD CONSTRAINT "beta_feature_allowances_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES public.beta_memberships ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_usage ADD CONSTRAINT "beta_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_feature_feedback ADD CONSTRAINT "beta_feature_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_lead_feedback ADD CONSTRAINT "beta_lead_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.analytics_events ADD CONSTRAINT "analytics_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_tutorial_progress ADD CONSTRAINT "beta_tutorial_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_discount_grants ADD CONSTRAINT "beta_discount_grants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.beta_testimonials ADD CONSTRAINT "beta_testimonials_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.user_search_runs ADD CONSTRAINT "user_search_runs_market_id_fkey" FOREIGN KEY ("market_id") REFERENCES public.markets ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.user_search_runs ADD CONSTRAINT "user_search_runs_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.company_intelligence ADD CONSTRAINT "company_intelligence_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.markets ADD CONSTRAINT "markets_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.workspace_invitations ADD CONSTRAINT "workspace_invitations_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE public.workspace_members ADD CONSTRAINT "workspace_members_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES public.workspaces ("id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
